// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyKMCfOIuNexjD-TPuu2T9ThiCTDGocUI',
    appId: '1:352624214565:web:72319d2918281fa4f135cc',
    messagingSenderId: '352624214565',
    projectId: 'flutter-chat-ab53d',
    authDomain: 'flutter-chat-ab53d.firebaseapp.com',
    storageBucket: 'flutter-chat-ab53d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj96dxclVP5h5EfcfgyRYiC1FNRkFeclU',
    appId: '1:352624214565:android:995e3d76c0710c30f135cc',
    messagingSenderId: '352624214565',
    projectId: 'flutter-chat-ab53d',
    storageBucket: 'flutter-chat-ab53d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTXTVZJwcqrrUngWQGihHDRroQFCMLXJE',
    appId: '1:352624214565:ios:d7dc7957931d53c8f135cc',
    messagingSenderId: '352624214565',
    projectId: 'flutter-chat-ab53d',
    storageBucket: 'flutter-chat-ab53d.firebasestorage.app',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTXTVZJwcqrrUngWQGihHDRroQFCMLXJE',
    appId: '1:352624214565:ios:d7dc7957931d53c8f135cc',
    messagingSenderId: '352624214565',
    projectId: 'flutter-chat-ab53d',
    storageBucket: 'flutter-chat-ab53d.firebasestorage.app',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyKMCfOIuNexjD-TPuu2T9ThiCTDGocUI',
    appId: '1:352624214565:web:fc3fafcb02820d34f135cc',
    messagingSenderId: '352624214565',
    projectId: 'flutter-chat-ab53d',
    authDomain: 'flutter-chat-ab53d.firebaseapp.com',
    storageBucket: 'flutter-chat-ab53d.firebasestorage.app',
  );
}
